# 11. 날짜/시간 처리

## 학습 목표
- `pd.to_datetime`으로 문자열을 날짜로 변환할 수 있다
- `dt` accessor로 연/월/일/요일을 추출할 수 있다
- 날짜 기간으로 필터링할 수 있다
- `resample`로 월별/주별 집계를 할 수 있다

---

## 왜 배워야 하나요?

실무 데이터의 대부분에는 **날짜 컬럼**이 있습니다.
- 월별/분기별 매출 추이
- 요일별 주문 패턴
- 특정 기간 데이터 필터링

날짜 타입으로 변환해두면 이런 분석이 매우 편해집니다. 문자열 상태로는 못 합니다.

In [ ]:
# 아래에 코드를 작성하세요

---
## 1. 문자열 → 날짜 변환

In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('./data/all_data.csv', index_col= 0)

In [6]:
df.head()

,주문번호,주문일자,고객ID,상품코드,수량,상품명,카테고리,단가,매출,고객명,성별,연령,지역,가입일,회원등급
0,ORD00001,2024-01-02,C019,P001,3,노트북,컴퓨터,1350000,4050000,엄정화,여,54,대전,2022-04-01,골드
1,ORD00002,2024-01-03,C028,P013,3,이어폰,음향,55000,165000,김유정,여,53,서울,2022-05-16,실버
2,ORD00003,2024-01-04,C026,P002,3,무선마우스,주변기기,35000,105000,김민수,여,27,경기,2022-05-06,실버
3,ORD00004,2024-01-05,C037,P004,2,27인치모니터,컴퓨터,450000,900000,고윤정,여,54,경기,2022-06-30,골드
4,ORD00005,2024-01-06,C026,P014,2,태블릿,컴퓨터,680000,1360000,김민수,여,27,경기,2022-05-06,실버

In [9]:
df['주문일자'] = pd.to_datetime( df['주문일자'] )

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 750 entries, 0 to 749
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   주문번호    750 non-null    object
 1   주문일자    750 non-null    datetime64[ns]
 2   고객ID    750 non-null    object
 3   상품코드    750 non-null    object
 4   수량      750 non-null    int64
 5   상품명     750 non-null    object
 6   카테고리    750 non-null    object
 7   단가      750 non-null    int64
 8   매출      750 non-null    int64
 9   고객명     750 non-null    object
 10  성별      750 non-null    object
 11  연령      750 non-null    int64
 12  지역      750 non-null    object
 13  가입일     750 non-null    object
 14  회원등급    750 non-null    object
dtypes: datetime64[ns](1), int64(4), object(10)
memory usage: 93.8+ KB

---
## 2. `dt` accessor - 날짜 요소 추출

`.dt.year`, `.dt.month`, `.dt.day`, `.dt.dayofweek` 등 다양한 요소를 꺼낼 수 있습니다.

In [15]:
df['년도']  =  df['주문일자'].dt.year

In [16]:
df.head(1)

,주문번호,주문일자,고객ID,상품코드,수량,상품명,카테고리,단가,매출,고객명,성별,연령,지역,가입일,회원등급,년도
0,ORD00001,2024-01-02,C019,P001,3,노트북,컴퓨터,1350000,4050000,엄정화,여,54,대전,2022-04-01,골드,2024

In [19]:
df['월'] = df['주문일자'].dt.month

In [23]:
df['날짜'] = df['주문일자'].dt.day

In [28]:
# 0 : 월요일,  1 : 화요일, ...  6 : 일요일
df['요일'] = df['주문일자'].dt.dayofweek

---
## 3. 날짜 필터링

In [31]:
# 1분기 주문 데이터를 가져오세요. 
df[ (df['월'] >= 1 ) & (df['월'] <= 3) ]

,주문번호,주문일자,고객ID,상품코드,수량,상품명,카테고리,단가,매출,고객명,성별,연령,지역,가입일,회원등급,년도,월,날짜,요일
0,ORD00001,2024-01-02,C019,P001,3,노트북,컴퓨터,1350000,4050000,엄정화,여,54,대전,2022-04-01,골드,2024,1,2,1
1,ORD00002,2024-01-03,C028,P013,3,이어폰,음향,55000,165000,김유정,여,53,서울,2022-05-16,실버,2024,1,3,2
2,ORD00003,2024-01-04,C026,P002,3,무선마우스,주변기기,35000,105000,김민수,여,27,경기,2022-05-06,실버,2024,1,4,3
3,ORD00004,2024-01-05,C037,P004,2,27인치모니터,컴퓨터,450000,900000,고윤정,여,54,경기,2022-06-30,골드,2024,1,5,4
4,ORD00005,2024-01-06,C026,P014,2,태블릿,컴퓨터,680000,1360000,김민수,여,27,경기,2022-05-06,실버,2024,1,6,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,ORD00146,2024-03-27,C022,P007,1,블루투스스피커,음향,120000,120000,조인성,여,58,대전,2022-04-16,일반,2024,3,27,2
146,ORD00147,2024-03-27,C013,P008,3,외장SSD,저장장치,95000,285000,송강,여,27,서울,2022-03-02,골드,2024,3,27,2
147,ORD00148,2024-03-27,C019,P012,1,보조배터리,액세서리,38000,38000,엄정화,여,54,대전,2022-04-01,골드,2024,3,27,2
148,ORD00149,2024-03-29,C049,P005,3,USB허브,주변기기,25000,75000,도경수,남,28,서울,2022-08-29,일반,2024,3,29,4
149,ORD00150,2024-03-30,C036,P002,3,무선마우스,주변기기,35000,105000,박철수,여,46,서울,2022-06-25,VIP,2024,3,30,5

In [36]:
df[ df['요일'] == 4 ]['매출'].sum()

np.int64(33246000)

---
## 4. 월별/요일별 집계

In [41]:
# 각 월별로 매출총합 구해줘
df.groupby('월')['매출'].sum()

월
1     23286000
2     37053000
3     11873000
4     16230000
5     28544000
6     28213000
7     28748000
8     16444000
9     15883000
10    40639000
11    23324000
12    29191000
Name: 매출, dtype: int64

In [43]:
# 요일별로 주문건수를 확인하고 싶다.  어느요일에 주문이 많나????
df.groupby('요일')['주문번호'].count()

요일
0    109
1    108
2    112
3    127
4    111
5     91
6     92
Name: 주문번호, dtype: int64

In [46]:
df['요일'].value_counts()

요일
3    127
2    112
4    111
0    109
1    108
6     92
5     91
Name: count, dtype: int64

---
## 5. `resample` - 시계열 재샘플링

날짜를 인덱스로 설정하면 `resample`로 월별/주별 집계를 더 편하게 할 수 있습니다.

In [47]:
df.head(2)

,주문번호,주문일자,고객ID,상품코드,수량,상품명,카테고리,단가,매출,고객명,성별,연령,지역,가입일,회원등급,년도,월,날짜,요일
0,ORD00001,2024-01-02,C019,P001,3,노트북,컴퓨터,1350000,4050000,엄정화,여,54,대전,2022-04-01,골드,2024,1,2,1
1,ORD00002,2024-01-03,C028,P013,3,이어폰,음향,55000,165000,김유정,여,53,서울,2022-05-16,실버,2024,1,3,2

In [49]:
# 1. 시간컬럼을 인덱스로 만든다.
df = df.set_index('주문일자')

In [50]:
df.head(3)

,주문번호,고객ID,상품코드,수량,상품명,카테고리,단가,매출,고객명,성별,연령,지역,가입일,회원등급,년도,월,날짜,요일
주문일자,,,,,,,,,,,,,,,,,,
2024-01-02,ORD00001,C019,P001,3,노트북,컴퓨터,1350000,4050000,엄정화,여,54,대전,2022-04-01,골드,2024,1,2,1
2024-01-03,ORD00002,C028,P013,3,이어폰,음향,55000,165000,김유정,여,53,서울,2022-05-16,실버,2024,1,3,2
2024-01-04,ORD00003,C026,P002,3,무선마우스,주변기기,35000,105000,김민수,여,27,경기,2022-05-06,실버,2024,1,4,3

In [51]:
# 2. 시간컬럼을 인덱스로 만들면, 
#    일단위, 주단위, 월말단위, 분기말 단위, 연말 단위, 초단위, 분단위, 시간단위로 데이터 분석가능
#    옵션: "D"(일), "W"(주), "ME"(월말), "QE"(분기말), "YE"(연말)

In [53]:
# 월말단위로 매출 총합을 구하라.
df['매출'].resample('ME').sum()

주문일자
2024-01-31    23286000
2024-02-29    37053000
2024-03-31    11873000
2024-04-30    16230000
2024-05-31    28544000
2024-06-30    28213000
2024-07-31    28748000
2024-08-31    16444000
2024-09-30    15883000
2024-10-31    40639000
2024-11-30    23324000
2024-12-31    29191000
Freq: ME, Name: 매출, dtype: int64

In [55]:
# 주 단위로 매출 총합을 구하라
df['매출'].resample('W').sum()

주문일자
2024-01-07     8130000
2024-01-14     1663000
2024-01-21     6952000
2024-01-28     5006000
2024-02-04    12962000
2024-02-11     5645000
2024-02-18     9572000
2024-02-25     6014000
2024-03-03     5699000
2024-03-10     5248000
2024-03-17     1679000
2024-03-24     2475000
2024-03-31     1167000
2024-04-07     5778000
2024-04-14     3379000
2024-04-21     3610000
2024-04-28     1753000
2024-05-05     2789000
2024-05-12     6346000
2024-05-19      502000
2024-05-26    13618000
2024-06-02     8576000
2024-06-09     9510000
2024-06-16     2619000
2024-06-23     1617000
2024-06-30    12890000
2024-07-07     7326000
2024-07-14     4909000
2024-07-21     7251000
2024-07-28     7797000
2024-08-04     4465000
2024-08-11     4823000
2024-08-18     3598000
2024-08-25     1395000
2024-09-01     3848000
2024-09-08     2215000
2024-09-15     1872000
2024-09-22     6733000
2024-09-29     4572000
2024-10-06    16636000
2024-10-13     6734000
2024-10-20     7967000
2024-10-27     8367000
2024-11-03     4249000
2024-11-10     1604000
2024-11-17     8675000
2024-11-24     7230000
2024-12-01     3702000
2024-12-08     5541000
2024-12-15     8277000
2024-12-22     5703000
2024-12-29     7341000
2025-01-05     1399000
Freq: W-SUN, Name: 매출, dtype: int64

---
## 실습문제

> 공통 준비:
> ```python
> import glob
> orders = pd.concat([pd.read_csv(f) for f in sorted(glob.glob("../data/orders_q*.csv"))], ignore_index=True)
> products = pd.read_csv("../data/products.csv")
> df = orders.merge(products, on="상품코드")
> df["매출"] = df["수량"] * df["단가"]
> df["주문일자"] = pd.to_datetime(df["주문일자"])
> ```

### 문제 1. 월별 매출 추이

월별 매출 합계와 주문 건수를 구하세요.

In [57]:
# df 를 이용해서 풀면 됩니다.

df.groupby('월').agg( 매출합계=('매출','sum')  ,  주문건수=('주문번호','count')  )

        매출합계  주문건수
월
1   23286000    55
2   37053000    58
3   11873000    37
4   16230000    66
5   28544000    56
6   28213000    58
7   28748000    72
8   16444000    63
9   15883000    65
10  40639000    87
11  23324000    67
12  29191000    66

### 문제 2. 요일별 주문 패턴

요일(0=월~6=일)별 주문 건수를 구하고, 가장 주문이 많은 요일을 출력하세요.

In [60]:
# 아래에 코드를 작성하세요
df['요일'].value_counts()

요일
3    127
2    112
4    111
0    109
1    108
6     92
5     91
Name: count, dtype: int64

### 문제 3. 특정 기간 매출

2024년 3월 한 달간의 총 매출을 구하세요.

In [66]:
# 아래에 코드를 작성하세요
df[ df['월'] == 3 ]['매출'].sum()

np.int64(11873000)

### 문제 4. resample로 주별 매출

`resample("W")`로 주별 매출 합계를 구하고, 매출이 가장 높은 주의 날짜를 출력하세요.

In [69]:
df['매출'].resample('W').sum()

주문일자
2024-01-07     8130000
2024-01-14     1663000
2024-01-21     6952000
2024-01-28     5006000
2024-02-04    12962000
2024-02-11     5645000
2024-02-18     9572000
2024-02-25     6014000
2024-03-03     5699000
2024-03-10     5248000
2024-03-17     1679000
2024-03-24     2475000
2024-03-31     1167000
2024-04-07     5778000
2024-04-14     3379000
2024-04-21     3610000
2024-04-28     1753000
2024-05-05     2789000
2024-05-12     6346000
2024-05-19      502000
2024-05-26    13618000
2024-06-02     8576000
2024-06-09     9510000
2024-06-16     2619000
2024-06-23     1617000
2024-06-30    12890000
2024-07-07     7326000
2024-07-14     4909000
2024-07-21     7251000
2024-07-28     7797000
2024-08-04     4465000
2024-08-11     4823000
2024-08-18     3598000
2024-08-25     1395000
2024-09-01     3848000
2024-09-08     2215000
2024-09-15     1872000
2024-09-22     6733000
2024-09-29     4572000
2024-10-06    16636000
2024-10-13     6734000
2024-10-20     7967000
2024-10-27     8367000
2024-11-03     4249000
2024-11-10     1604000
2024-11-17     8675000
2024-11-24     7230000
2024-12-01     3702000
2024-12-08     5541000
2024-12-15     8277000
2024-12-22     5703000
2024-12-29     7341000
2025-01-05     1399000
Freq: W-SUN, Name: 매출, dtype: int64

In [71]:
df.to_csv('./data/all_data.csv')

In [ ]:
# 아래에 코드를 작성하세요